### PR TITLE
Unify pagefind code and disable subresults

### PR DESCRIPTION
**Pull request by smallketchup82**
sorry seaswimmer but i needed to do this to at least make the site bearable

### CODE REVIEW

**Review by cswimr — DISMISSED** [review]
LGTM  
###### why bro now i have merge conflicts to resolve on my branch :sob:

**Comment by cswimr** [comment]
oh format with prettier before merging please

**Comment by smallketchup82** [comment]
bbbut the -15 loc!!!

**Review by cswimr — APPROVED** [review]
LGTM for real this time

**Pull request merged**
