### PR TITLE
Switch to Cloudflare Pages

### PR DESCRIPTION
**Pull request by cswimr**
This PR switches our build workflows to use Cloudflare Pages instead of GitHub Pages. I can't easily test this without merging this though unfortunately.

## Known Issues:
- Hugo's BaseURL will be incorrect on Preview Deployments. This is because we are not using Cloudflare Pages' Builder, so we don't know what the URL to the Preview Deployment will be until after the site is deployed. So, in Preview Deployments, `RelURL` and `AbsURL` will use the production BaseURL of `https://v2.galaxypedia.org`.

### CODE REVIEW

**Comment by smallketchup82** [comment]
how tf did you request review of a team whattttttt

**Comment by smallketchup82** [comment]
oh whaaaaaa i can also do it now. shits so weird

**Comment by smallketchup82** [comment]
> I can't easily test this without merging this though unfortunately.

real men test in prod

**Comment by cswimr** [comment]
> how tf did you request review of a team whattttttt

it's because I added a [CODEOWNERS](https://github.com/Galaxypedia-Wiki/Galaxypedia/blob/main/.github/CODEOWNERS) file a few pr's ago, so now teams have ownership of files in this repository and will automatically be asked to review prs of files they own

**Pull request merged**
